Parameters:
  ConnectionArn:
    Description: The CodeConnections ARN for your source repository.
    Type: String
  FullRepositoryId:
    Description: The full repository ID to use with your CodeConnections connection.
    Type: String
  BranchName:
    Description: The branch name to use with your CodeConnections connection.
    Type: String
  CodePipelineName:
    Description: The CodePipeline pipeline name that will deploy to your CloudFormation stack.
    Type: String
    Default: DeployToCloudFormationService
  StackName:
    Description: The CloudFormation stack name that you want to create or update.
    Type: String
  TemplatePath:
    Description: The path in your source repository to the CloudFormation template file to create or update your stack.
    Type: String
  OutputFileName:
    Description: The path the output from the CloudFormation stack update will be written to.
    Type: String
    Default: output.json
  CloudFormationResourcePermissions:
    Description: The permission required by CloudFormation to make resource calls on your behalf.
    Type: String
  RetentionPolicy:
    Description: Define if you'd like the resource retained or deleted when the
      CloudFormation stack is deleted.
    Type: String
    Default: Delete
    AllowedValues:
      - Delete
      - Retain
  TemplateConfiguration:
    Description: The path to a template configuration file containing parameter values and stack policy for creating or updating your stack.
    Type: String
    Default: ''
  ParameterOverrides:
    Description: A JSON string to provide parameter values that override defaults in the template or TemplateConfiguration file.
    Type: String
    Default: ''
Conditions:
  HasTemplateConfiguration: !Not [!Equals ['', !Ref TemplateConfiguration]]
  HasParameterOverrides: !Not [!Equals ['', !Ref ParameterOverrides]]
Resources:
  CodePipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: !Ref RetentionPolicy
    DeletionPolicy: !Ref RetentionPolicy
  CodePipelineArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodePipelineArtifactsBucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Effect: Deny
            Principal:
              AWS: '*'
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - '/'
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
        Version: '2012-10-17'
