AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple Lambda function deployed via CloudFormation

Parameters:
  ObjectName:
    Description: The object name you want to use.
    Type: String
    Default: "tiger-demo-2"
  DeployStack:
    Type: String
    Default: true

# Conditions:
#   DoesItDeploy: [!Equals ['', !Ref DeployStack]]



Resources:
  MyLambdaRole:    
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ObjectName}-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole' # Provides basic CloudWatch logging permissions
      Policies:
        - PolicyName: S3Permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: "Allow S3 Access"
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListObject
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::tiger-demo-2025

  MyPythonLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref ObjectName
      Handler: index.lambda_handler # 'index' is the file name, 'lambda_handler' is the function name
      Runtime: python3.9 # Specify your desired Python runtime version
      Code:
        ZipFile: |
          import json
          print('Loading function')
          def lambda_handler(event, context):
              #print("Received event: " + json.dumps(event, indent=2))
              print("value1 = " + event['key1'])
              print("value2 = " + event['key2'])
              print("value3 = " + event['key3'])
              return event['key1']  # Echo back the first key value
              #raise Exception('Something went wrong')

      Role: !GetAtt MyLambdaRole.Arn # References the ARN of the IAM role created above
      MemorySize: 128 # Optional: Adjust memory as needed
      Timeout: 30 # Optional: Adjust timeout in seconds as needed
      Tags: # Optional: Add tags for organization
        - Key: Environment
          Value: Dev
        - Key: Project
          Value: MyLambdaProject

Outputs:
  LambdaFunctionName: 
    Description: The name of the deployed Lambda function
    Value: !Ref MyPythonLambdaFunction
  LambdaFunctionArn:
    Description: The ARN of the deployed Lambda function
    Value: !GetAtt MyPythonLambdaFunction.Arn